export const UPDATE_CHARACTERS_FETCHING = 'UPDATE_CHARACTERS_FETCHING';
export const UPDATE_CHARACTERS_LIST = 'UPDATE_CHARACTERS_LIST';
export const UPDATE_CHARACTERS_ITEM = 'UPDATE_CHARACTERS_ITEM';
